# Generated by Django 3.1.2 on 2020-10-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], max_length=10),
        ),
    ]
