# Generated by Django 3.1.2 on 2020-10-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Cambios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_antigua', models.IntegerField()),
                ('cantidad_nueva', models.IntegerField()),
                ('motivo', models.CharField(max_length=150)),
                ('bodeguero', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial_Cambio',
                'verbose_name_plural': 'Historial_Cambios',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
