# Generated by Django 3.1.2 on 2020-10-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20201025_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_cambios',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
    ]
