# Generated by Django 3.1.2 on 2020-10-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_historial_cambios_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTransferenciaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodeguero', models.CharField(max_length=50)),
                ('tipo_transferencia', models.CharField(choices=[('INTERNAS', 'INTERNAS'), ('EXTERNAS', 'EXTERNAS')], max_length=20)),
                ('bodega_origen', models.CharField(max_length=50)),
                ('bodega_destino', models.CharField(max_length=50)),
                ('estado_transferencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
                ('transferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.solicitudtransferenciaproductos')),
            ],
        ),
    ]
