# Generated by Django 3.1.2 on 2020-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_detalletransferencias_solicitudtransferenciaproductos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtransferenciaproductos',
            name='bodeguero',
        ),
        migrations.AddField(
            model_name='solicitudtransferenciaproductos',
            name='aceptador',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudtransferenciaproductos',
            name='repartidor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudtransferenciaproductos',
            name='solicitante',
            field=models.CharField(default='Usuario Bodeguero', max_length=50),
            preserve_default=False,
        ),
    ]
