# Generated by Django 3.1.2 on 2020-10-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20201025_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtransferenciaproductos',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA', 'ACEPTADA'), ('COMPLETADA', 'COMPLETADA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudtransferenciaproductos',
            name='tipo_transferencia',
            field=models.CharField(choices=[('INTERNA', 'INTERNA'), ('EXTERNA', 'EXTERNA')], max_length=20),
        ),
    ]
