# Generated by Django 3.1.2 on 2020-10-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repartidor', '0001_initial'),
        ('producto', '0006_auto_20201027_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtransferenciaproductos',
            name='repartidor',
        ),
        migrations.AddField(
            model_name='solicitudtransferenciaproductos',
            name='repartidor_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repartidor.repartidor'),
        ),
    ]
