# Generated by Django 3.1.2 on 2020-10-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20201026_1704'),
        ('producto', '0006_auto_20201027_0054'),
    ]

    operations = [
    ]
