# Generated by Django 3.1.2 on 2020-10-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20201027_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtransferenciaproductos',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA', 'ACEPTADA'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', editable=False, max_length=20),
        ),
    ]
