# Generated by Django 3.1.2 on 2020-10-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20201027_1957'),
        ('producto', '0007_merge_20201027_2003'),
    ]

    operations = [
    ]
