# Generated by Django 3.1.2 on 2020-10-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_merge_20201028_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtransferenciaproductos',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADA', 'ACEPTADA'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', editable=False, max_length=20),
        ),
    ]
