# Generated by Django 3.1.2 on 2020-10-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_auto_20201027_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='departamento',
        ),
    ]
