# Generated by Django 3.1.2 on 2020-10-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0006_auto_20201026_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
            options={
                'verbose_name': 'ListaProducto',
                'verbose_name_plural': 'ListaProductos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orden', models.IntegerField()),
                ('cliente', models.CharField(max_length=150)),
                ('vendedor', models.CharField(max_length=20)),
                ('fecha_facturacion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('lista_productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionVentas.listaproductos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
