# Generated by Django 3.1.2 on 2020-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0002_auto_20201026_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='lista_productos',
        ),
        migrations.AddField(
            model_name='listaproductos',
            name='no_orden',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
