# Generated by Django 3.1.2 on 2020-10-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0003_auto_20201026_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('DOMICILIO', 'DOMICILIO')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
