# Generated by Django 3.1.2 on 2020-10-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0004_venta_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaproductos',
            name='subtotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
