# Generated by Django 3.1.2 on 2020-10-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0005_listaproductos_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaproductos',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
