# Generated by Django 3.1.2 on 2020-10-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0006_listaproductos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaproductos',
            name='no_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionVentas.venta'),
        ),
    ]
