# Generated by Django 3.1.2 on 2020-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0007_auto_20201027_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='no_orden',
            field=models.CharField(max_length=50),
        ),
    ]
