# Generated by Django 3.1.2 on 2020-10-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0008_auto_20201027_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaproductos',
            name='no_orden',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
