# Generated by Django 3.1.2 on 2020-10-28 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionVentas', '0009_auto_20201027_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='repartidor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
