# Generated by Django 3.1.2 on 2020-10-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0010_venta_repartidor_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO')], default='PENDIENTE', editable=False, max_length=20),
        ),
    ]
