# Generated by Django 3.1.2 on 2020-10-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0011_venta_estado_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_transferencia',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO')], default='PENDIENTE', max_length=20),
        ),
    ]
